name: NUnit Tests and Deploy Allure Reports
on:
  push:
    branches:
      - main    
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Test 
        run: dotnet test
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4.0.0
        with:
          name: allure-results
          path: .\bin\Debug\net8.0\allure-results
          if-no-files-found: error
          retention-days: 20
  report:
    needs: test
  
    runs-on: ubuntu-latest
  
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4.1.0
        with:
          name: allure-results
          path: ./allure-results
  
      - name: Get Allure history (optional)
        uses: actions/checkout@v4.1.1
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
  
      - name: Load Allure test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure test report
        uses: simple-elf/allure-report-action@master
        id: allure-report
        if: always()
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Publish Allure test report
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ always() && (steps.allure-report.outcome == 'success') }}
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_branch: gh-pages
         publish_dir: ${{ steps.allure-report.outputs.reports-site }}
         destination_dir: ${{ steps.allure-report.outputs.reports-site-path }} 